### ISSUE TITLE
[META] PyCon US 2024 Prep

### ISSUE THREAD

**Issue by pavithraes** [Quansight/ragna-presentations#12]
- [x] Deploy instance after quote increase?
- [x] Create a new environment: `pycon-pycon-ragna`
- [x] Set new env as default for all notebooks
- [x] Make a note of env in the intro notebook.
- [x] Add llama3 to shared folder: `shared/pycon/models/turboderp/Llama-3-8B-Instruct-exl2`
- [x] Add openai api key to shared folder: `shared/pycon/.env`
- [x] Update the paths to model & api key in all notebooks

**Comment by dharhas** [comment]
created ~`global/pycon`~ `pycon/ragna` environment using env.yml listed in repo and added `CONDA_OVERRIDE_CUDA: '12.2'`
